// 単語まるごと書字練習（T036）向けの、代表単語（word）69件ぶんの英語の意味。
// [曖昧] 基礎的な語彙のため個別の一次資料検証はしていない（T034のwordフィールドと同水準）。
// 値が単語自身の文字列と一致する行が無いことを回帰テストで確認している。
export const EN_WORD_MEANING: Record<string, string> = {
  一月: 'January',
  七月: 'July',
  三月: 'March',
  上手: 'skillful',
  下手: 'unskillful',
  中学校: 'junior high school',
  九月: 'September',
  二月: 'February',
  五月: 'May',
  日本人: 'Japanese person',
  今日: 'today',
  休日: 'holiday',
  何時: 'what time',
  先生: 'teacher',
  入学: 'school enrollment',
  八月: 'August',
  六月: 'June',
  百円: '100 yen',
  出口: 'exit',
  半分: 'half',
  北海道: 'Hokkaido',
  十月: 'October',
  千円: '1000 yen',
  半年: 'half a year',
  南口: 'south exit',
  右手: 'right hand',
  名前: 'name',
  四月: 'April',
  土曜日: 'Saturday',
  外国人: 'foreigner',
  大学: 'university',
  女性: 'woman',
  子供: 'child',
  学校: 'school',
  小学校: 'elementary school',
  小川: 'stream',
  左手: 'left hand',
  今年: 'this year',
  日曜日: 'Sunday',
  時間: 'time',
  辞書: 'dictionary',
  月曜日: 'Monday',
  木曜日: 'Thursday',
  日本: 'Japan',
  来年: 'next year',
  東京: 'Tokyo',
  校長: 'principal',
  母国: 'home country',
  天気: 'weather',
  水曜日: 'Wednesday',
  火曜日: 'Tuesday',
  父親: 'father',
  学生: 'student',
  男性: 'man',
  百万: 'million',
  新聞: 'newspaper',
  旅行: 'travel',
  西口: 'west exit',
  花見: 'flower viewing',
  電話: 'telephone',
  読書: 'reading',
  電車: 'train',
  金曜日: 'Friday',
  社長: 'company president',
  人間: 'human being',
  雨天: 'rainy weather',
  電気: 'electricity',
  食事: 'meal',
  高校: 'high school',
};

export function getWordMeaning(word: string): string | null {
  return EN_WORD_MEANING[word] ?? null;
}
