#!/usr/bin/env node
// generate-kana-46.mjs
//
// ひらがな・カタカナの基本46字（五十音、濁音・半濁音・拗音は含まない）を
// KanjiVG から取り込み、既存の漢字データと同じ形式のファイル群を生成する。
//
// 書き順データ（strokes[].d）は KanjiVG（CC BY-SA 3.0）からの自動抽出のみを使う。
// 想像や推測で SVG パスを書くことは絶対に行わない（AGENTS.md 参照）。
//
// 使い方:
//   node scripts/generate-kana-46.mjs
//
// 動作:
//   1. 46 音ぶん、ひらがな・カタカナそれぞれについて
//      scripts/import-kanji.mjs をサブプロセスとして呼び出し、
//      KanjiVG から SVG を取得して src/lib/data/kanji/u{code}.js を生成する
//      （import-kanji.mjs は漢字専用ではなく、KanjiVG の命名規則
//      （コードポイント16進5桁）に従うファイルなら何でも取り込める）
//   2. 生成された各ファイルの reading / meaning / word を埋める
//      （ローマ字は標準的なヘボン式表記。書き順データではないため
//      想像禁止の対象外）
//   3. 46 字ずつをまとめた src/lib/data/kanji/kana-46.js を生成する
//      （KANJI_HIRAGANA_46 / KANJI_KATAKANA_46 を export）
//
// 依存: Node 標準モジュールのみ。

import { promises as fs } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { execFileSync } from 'node:child_process';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const ROOT = path.resolve(__dirname, '..');
const KANJI_DIR = path.join(ROOT, 'src', 'lib', 'data', 'kanji');
const IMPORT_SCRIPT = path.join(ROOT, 'scripts', 'import-kanji.mjs');
const PACK_OUT = path.join(KANJI_DIR, 'kana-46.js');

// 五十音順（あ行→わ行→ん）。濁音・半濁音・拗音は対象外（第一段階のスコープ）。
// ローマ字はヘボン式（し=shi, ち=chi, つ=tsu, ふ=fu, を=wo）。
const GOJUON = [
  ['あ', 'ア', 'a'],
  ['い', 'イ', 'i'],
  ['う', 'ウ', 'u'],
  ['え', 'エ', 'e'],
  ['お', 'オ', 'o'],
  ['か', 'カ', 'ka'],
  ['き', 'キ', 'ki'],
  ['く', 'ク', 'ku'],
  ['け', 'ケ', 'ke'],
  ['こ', 'コ', 'ko'],
  ['さ', 'サ', 'sa'],
  ['し', 'シ', 'shi'],
  ['す', 'ス', 'su'],
  ['せ', 'セ', 'se'],
  ['そ', 'ソ', 'so'],
  ['た', 'タ', 'ta'],
  ['ち', 'チ', 'chi'],
  ['つ', 'ツ', 'tsu'],
  ['て', 'テ', 'te'],
  ['と', 'ト', 'to'],
  ['な', 'ナ', 'na'],
  ['に', 'ニ', 'ni'],
  ['ぬ', 'ヌ', 'nu'],
  ['ね', 'ネ', 'ne'],
  ['の', 'ノ', 'no'],
  ['は', 'ハ', 'ha'],
  ['ひ', 'ヒ', 'hi'],
  ['ふ', 'フ', 'fu'],
  ['へ', 'ヘ', 'he'],
  ['ほ', 'ホ', 'ho'],
  ['ま', 'マ', 'ma'],
  ['み', 'ミ', 'mi'],
  ['む', 'ム', 'mu'],
  ['め', 'メ', 'me'],
  ['も', 'モ', 'mo'],
  ['や', 'ヤ', 'ya'],
  ['ゆ', 'ユ', 'yu'],
  ['よ', 'ヨ', 'yo'],
  ['ら', 'ラ', 'ra'],
  ['り', 'リ', 'ri'],
  ['る', 'ル', 'ru'],
  ['れ', 'レ', 're'],
  ['ろ', 'ロ', 'ro'],
  ['わ', 'ワ', 'wa'],
  ['を', 'ヲ', 'wo'],
  ['ん', 'ン', 'n'],
];

function codeOf(ch) {
  return ch.codePointAt(0).toString(16).padStart(5, '0');
}

function slugOf(ch) {
  return `u${codeOf(ch)}`;
}

function constOf(slug) {
  return `KANJI_${slug.toUpperCase()}`;
}

async function exists(p) {
  try {
    await fs.access(p);
    return true;
  } catch {
    return false;
  }
}

function runImport(ch) {
  const code = codeOf(ch);
  const slug = slugOf(ch);
  execFileSync(
    process.execPath,
    [IMPORT_SCRIPT, '--kanji', ch, '--code', code, '--name', slug, '--force'],
    { cwd: ROOT, stdio: 'inherit' },
  );
  return slug;
}

// reading / meaning / word を埋める。strokes（書き順）には一切触れない。
async function patchKanaFile(filePath, { char, romaji, kind }) {
  let src = await fs.readFile(filePath, 'utf8');
  src = src.replace(/^(\s*reading:\s*).*,?(\s*(?:\/\/.*)?)$/m, `$1'${romaji}',$2`);
  src = src.replace(
    /^(\s*meaning:\s*).*,?(\s*(?:\/\/.*)?)$/m,
    `$1'${kind === 'hiragana' ? 'ひらがな' : 'カタカナ'}「${char}」（ローマ字: ${romaji}）',$2`,
  );
  src = src.replace(/^(\s*word:\s*).*,?(\s*(?:\/\/.*)?)$/m, `$1'${char}',$2`);
  // import-kanji.mjs が付ける「動作語: 未取得」の注記は、覚え歌機能自体を
  // 使わないひらがな・カタカナには不要なので削る。
  src = src.replace(/^\/\/ 動作語: 未取得.*\n/m, '');
  await fs.writeFile(filePath, src, 'utf8');
}

function buildPack(hiraDefs, kataDefs) {
  const allDefs = [...hiraDefs, ...kataDefs];
  const imports = allDefs
    .map((d) => `import { ${constOf(d.slug)} } from './${d.slug}.js';`)
    .join('\n');
  const hiraList = hiraDefs.map((d) => constOf(d.slug)).join(', ');
  const kataList = kataDefs.map((d) => constOf(d.slug)).join(', ');
  return `// Auto-generated by scripts/generate-kana-46.mjs
// ひらがな・カタカナ基本46字（五十音）。濁音・半濁音・拗音は含まない。
// 書き順データ（strokes）の出典は各ファイル先頭コメントの通り KanjiVG（CC BY-SA 3.0）。
${imports}

export const KANJI_HIRAGANA_46 = [${hiraList}];
export const KANJI_KATAKANA_46 = [${kataList}];
`;
}

async function main() {
  await fs.mkdir(KANJI_DIR, { recursive: true });

  const hiraDefs = [];
  const kataDefs = [];
  let generated = 0;

  for (const [hira, kata, romaji] of GOJUON) {
    for (const [ch, kind, defs] of [
      [hira, 'hiragana', hiraDefs],
      [kata, 'katakana', kataDefs],
    ]) {
      const slug = slugOf(ch);
      const filePath = path.join(KANJI_DIR, `${slug}.js`);
      if (!(await exists(filePath))) {
        runImport(ch);
        generated++;
      }
      await patchKanaFile(filePath, { char: ch, romaji, kind });
      defs.push({ char: ch, slug });
    }
  }

  await fs.writeFile(PACK_OUT, buildPack(hiraDefs, kataDefs), 'utf8');
  console.log(
    JSON.stringify(
      { generated, hiragana: hiraDefs.length, katakana: kataDefs.length, pack: PACK_OUT },
      null,
      2,
    ),
  );
}

main().catch((err) => {
  console.error('[generate-kana-46] 失敗:', err);
  process.exit(1);
});
